/// 平台上所有合約的自訂 error——由 scripts/gen-error-abi.mjs 產生，請勿手改。
///
/// 用途只有一個：**把 revert 的四個位元組翻譯成人看得懂的字**。
///
/// 前端其他的 ABI 常數都只放 function，因為呼叫只需要那些；
/// 但 revert 回來的是一個 selector，沒有對應的 error 定義就解不開，
/// 使用者看到的會是 `0x5c0dee5d` 這種東西。`PasskeyAccount.execute` 尤其嚴重：
/// 它把真正的錯誤包在 `CallFailed(index, reason)` 的 reason 裡，
/// 不拆開就等於把診斷資訊整個丟掉。
///
/// 合約改了自訂 error 就要重跑：`cd web && node scripts/gen-error-abi.mjs`

export const errorAbi = [
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  { type: "error", name: "AccessControlUnauthorizedAccount", inputs: [{ name: "account", type: "address" }, { name: "neededRole", type: "bytes32" }] },
  { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address" }] },
  { type: "error", name: "AlreadyAttested", inputs: [{ name: "reportId", type: "uint256" }] },
  { type: "error", name: "AlreadyUnlocked", inputs: [] },
  { type: "error", name: "AttestationAlreadyUsed", inputs: [{ name: "attestationId", type: "uint256" }] },
  { type: "error", name: "AttestationExpired", inputs: [] },
  { type: "error", name: "BatchIsFrozen", inputs: [{ name: "batchId", type: "uint256" }] },
  { type: "error", name: "BelowMinFill", inputs: [] },
  { type: "error", name: "BidInactive", inputs: [{ name: "bidId", type: "uint256" }] },
  { type: "error", name: "CallFailed", inputs: [{ name: "index", type: "uint256" }, { name: "reason", type: "bytes" }] },
  { type: "error", name: "CannotFillOwnBid", inputs: [] },
  { type: "error", name: "CannotUpdateEmptyPosition", inputs: [] },
  { type: "error", name: "CountryMismatch", inputs: [{ name: "wanted", type: "bytes2" }, { name: "got", type: "bytes2" }] },
  { type: "error", name: "Create2EmptyBytecode", inputs: [] },
  { type: "error", name: "CurrenciesOutOfOrderOrEqual", inputs: [{ name: "currency0", type: "address" }, { name: "currency1", type: "address" }] },
  { type: "error", name: "CurrencyNotSettled", inputs: [] },
  { type: "error", name: "DailyLimitExceeded", inputs: [{ name: "account", type: "address" }, { name: "attempted", type: "uint256" }, { name: "limit", type: "uint256" }] },
  { type: "error", name: "DelegateCallNotAllowed", inputs: [] },
  { type: "error", name: "DeployerHasNoFunds", inputs: [{ name: "deployer", type: "address" }, { name: "chainId", type: "uint256" }] },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  { type: "error", name: "ECDSAInvalidSignatureLength", inputs: [{ name: "length", type: "uint256" }] },
  { type: "error", name: "ECDSAInvalidSignatureS", inputs: [{ name: "s", type: "bytes32" }] },
  { type: "error", name: "ERC1155InsufficientBalance", inputs: [{ name: "sender", type: "address" }, { name: "balance", type: "uint256" }, { name: "needed", type: "uint256" }, { name: "tokenId", type: "uint256" }] },
  { type: "error", name: "ERC1155InvalidApprover", inputs: [{ name: "approver", type: "address" }] },
  { type: "error", name: "ERC1155InvalidArrayLength", inputs: [{ name: "idsLength", type: "uint256" }, { name: "valuesLength", type: "uint256" }] },
  { type: "error", name: "ERC1155InvalidOperator", inputs: [{ name: "operator", type: "address" }] },
  { type: "error", name: "ERC1155InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
  { type: "error", name: "ERC1155InvalidSender", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "ERC1155MissingApprovalForAll", inputs: [{ name: "operator", type: "address" }, { name: "owner", type: "address" }] },
  { type: "error", name: "ERC1967InvalidAdmin", inputs: [{ name: "admin", type: "address" }] },
  { type: "error", name: "ERC1967InvalidBeacon", inputs: [{ name: "beacon", type: "address" }] },
  { type: "error", name: "ERC1967InvalidImplementation", inputs: [{ name: "implementation", type: "address" }] },
  { type: "error", name: "ERC1967NonPayable", inputs: [] },
  { type: "error", name: "ERC20InsufficientAllowance", inputs: [{ name: "spender", type: "address" }, { name: "allowance", type: "uint256" }, { name: "needed", type: "uint256" }] },
  { type: "error", name: "ERC20InsufficientBalance", inputs: [{ name: "sender", type: "address" }, { name: "balance", type: "uint256" }, { name: "needed", type: "uint256" }] },
  { type: "error", name: "ERC20InvalidApprover", inputs: [{ name: "approver", type: "address" }] },
  { type: "error", name: "ERC20InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
  { type: "error", name: "ERC20InvalidSender", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "ERC20InvalidSpender", inputs: [{ name: "spender", type: "address" }] },
  { type: "error", name: "ERC20TransferFailed", inputs: [] },
  { type: "error", name: "ERC721IncorrectOwner", inputs: [{ name: "sender", type: "address" }, { name: "tokenId", type: "uint256" }, { name: "owner", type: "address" }] },
  { type: "error", name: "ERC721InsufficientApproval", inputs: [{ name: "operator", type: "address" }, { name: "tokenId", type: "uint256" }] },
  { type: "error", name: "ERC721InvalidApprover", inputs: [{ name: "approver", type: "address" }] },
  { type: "error", name: "ERC721InvalidOperator", inputs: [{ name: "operator", type: "address" }] },
  { type: "error", name: "ERC721InvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "ERC721InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
  { type: "error", name: "ERC721InvalidSender", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "ERC721NonexistentToken", inputs: [{ name: "tokenId", type: "uint256" }] },
  { type: "error", name: "EmptyReport", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExceedsRemaining", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "FailedCall", inputs: [] },
  { type: "error", name: "FailedDeployment", inputs: [] },
  { type: "error", name: "FeeTooHigh", inputs: [] },
  { type: "error", name: "FeeTooHigh", inputs: [{ name: "bps", type: "uint16" }] },
  { type: "error", name: "Frozen", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "HookAddressNotValid", inputs: [{ name: "hooks", type: "address" }] },
  { type: "error", name: "HookCallFailed", inputs: [] },
  { type: "error", name: "HookDeltaExceedsSwapAmount", inputs: [] },
  { type: "error", name: "HookNotImplemented", inputs: [] },
  { type: "error", name: "IdentityMismatch", inputs: [] },
  { type: "error", name: "IndividualRetireDisabled", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "IndividualTransferDisabled", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "InsufficientBalance", inputs: [{ name: "balance", type: "uint256" }, { name: "needed", type: "uint256" }] },
  { type: "error", name: "InsufficientLiquidity", inputs: [] },
  { type: "error", name: "InsufficientPooled", inputs: [{ name: "batchId", type: "uint256" }] },
  { type: "error", name: "InvalidAttestation", inputs: [] },
  { type: "error", name: "InvalidCaller", inputs: [] },
  { type: "error", name: "InvalidFeeForExactOut", inputs: [] },
  { type: "error", name: "InvalidHookResponse", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "InvalidPeriod", inputs: [] },
  { type: "error", name: "InvalidPoolPair", inputs: [] },
  { type: "error", name: "InvalidPrice", inputs: [] },
  { type: "error", name: "InvalidPriceOrLiquidity", inputs: [] },
  { type: "error", name: "InvalidShortString", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidSqrtPrice", inputs: [{ name: "sqrtPriceX96", type: "uint160" }] },
  { type: "error", name: "InvalidTick", inputs: [{ name: "tick", type: "int24" }] },
  { type: "error", name: "InvalidTier", inputs: [] },
  { type: "error", name: "JurisdictionDisabled", inputs: [{ name: "country", type: "bytes2" }] },
  { type: "error", name: "LPFeeTooLarge", inputs: [{ name: "fee", type: "uint24" }] },
  { type: "error", name: "ManagerLocked", inputs: [] },
  { type: "error", name: "MissingPrecompile", inputs: [{ name: "", type: "address" }] },
  { type: "error", name: "MustClearExactPositiveDelta", inputs: [] },
  { type: "error", name: "NativeTransferFailed", inputs: [] },
  { type: "error", name: "NoLiquidityToReceiveFees", inputs: [] },
  { type: "error", name: "NoSwapOccurred", inputs: [] },
  { type: "error", name: "NonzeroNativeValue", inputs: [] },
  { type: "error", name: "NotActive", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "NotActiveAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "NotBuyer", inputs: [] },
  { type: "error", name: "NotCorporate", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "NotDomestic", inputs: [{ name: "country", type: "bytes2" }] },
  { type: "error", name: "NotEnoughLiquidity", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "NotPoolManager", inputs: [] },
  { type: "error", name: "NotSeller", inputs: [] },
  { type: "error", name: "OnlyKYC", inputs: [] },
  { type: "error", name: "OnlyRegistry", inputs: [] },
  { type: "error", name: "OrderInactive", inputs: [{ name: "orderId", type: "uint256" }] },
  { type: "error", name: "PoolAlreadyInitialized", inputs: [] },
  { type: "error", name: "PoolNotInitialized", inputs: [] },
  { type: "error", name: "PriceLimitAlreadyExceeded", inputs: [{ name: "sqrtPriceCurrentX96", type: "uint160" }, { name: "sqrtPriceLimitX96", type: "uint160" }] },
  { type: "error", name: "PriceLimitOutOfBounds", inputs: [{ name: "sqrtPriceLimitX96", type: "uint160" }] },
  { type: "error", name: "PriceOverflow", inputs: [] },
  { type: "error", name: "ProjectInactive", inputs: [{ name: "projectId", type: "uint256" }] },
  { type: "error", name: "ProtocolFeeCurrencySynced", inputs: [] },
  { type: "error", name: "ProtocolFeeTooLarge", inputs: [{ name: "fee", type: "uint24" }] },
  { type: "error", name: "PurposeNotAllowed", inputs: [{ name: "country", type: "bytes2" }, { name: "purpose", type: "uint8" }] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "RegistryAlreadySet", inputs: [] },
  { type: "error", name: "SafeCastOverflow", inputs: [] },
  { type: "error", name: "SafeCastOverflowedIntDowncast", inputs: [{ name: "bits", type: "uint8" }, { name: "value", type: "int256" }] },
  { type: "error", name: "SafeCastOverflowedIntToUint", inputs: [{ name: "value", type: "int256" }] },
  { type: "error", name: "SafeCastOverflowedUintDowncast", inputs: [{ name: "bits", type: "uint8" }, { name: "value", type: "uint256" }] },
  { type: "error", name: "SafeCastOverflowedUintToInt", inputs: [{ name: "value", type: "uint256" }] },
  { type: "error", name: "SafeERC20FailedDecreaseAllowance", inputs: [{ name: "spender", type: "address" }, { name: "currentAllowance", type: "uint256" }, { name: "requestedDecrease", type: "uint256" }] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address" }] },
  { type: "error", name: "SerialAlreadyUsed", inputs: [{ name: "serialHash", type: "bytes32" }] },
  { type: "error", name: "Soulbound", inputs: [] },
  { type: "error", name: "StringTooLong", inputs: [{ name: "str", type: "string" }] },
  { type: "error", name: "StringsInsufficientHexLength", inputs: [{ name: "value", type: "uint256" }, { name: "length", type: "uint256" }] },
  { type: "error", name: "SwapAmountCannotBeZero", inputs: [] },
  { type: "error", name: "TickLiquidityOverflow", inputs: [{ name: "tick", type: "int24" }] },
  { type: "error", name: "TickLowerOutOfBounds", inputs: [{ name: "tickLower", type: "int24" }] },
  { type: "error", name: "TickMisaligned", inputs: [{ name: "tick", type: "int24" }, { name: "tickSpacing", type: "int24" }] },
  { type: "error", name: "TickSpacingTooLarge", inputs: [{ name: "tickSpacing", type: "int24" }] },
  { type: "error", name: "TickSpacingTooSmall", inputs: [{ name: "tickSpacing", type: "int24" }] },
  { type: "error", name: "TickUpperOutOfBounds", inputs: [{ name: "tickUpper", type: "int24" }] },
  { type: "error", name: "TicksMisordered", inputs: [{ name: "tickLower", type: "int24" }, { name: "tickUpper", type: "int24" }] },
  { type: "error", name: "TimelockInsufficientDelay", inputs: [{ name: "delay", type: "uint256" }, { name: "minDelay", type: "uint256" }] },
  { type: "error", name: "TimelockInvalidOperationLength", inputs: [{ name: "targets", type: "uint256" }, { name: "payloads", type: "uint256" }, { name: "values", type: "uint256" }] },
  { type: "error", name: "TimelockUnauthorizedCaller", inputs: [{ name: "caller", type: "address" }] },
  { type: "error", name: "TimelockUnexecutedPredecessor", inputs: [{ name: "predecessorId", type: "bytes32" }] },
  { type: "error", name: "TimelockUnexpectedOperationState", inputs: [{ name: "operationId", type: "bytes32" }, { name: "expectedStates", type: "bytes32" }] },
  { type: "error", name: "TooLittleReceived", inputs: [{ name: "received", type: "uint256" }, { name: "minimum", type: "uint256" }] },
  { type: "error", name: "TooManyBatches", inputs: [{ name: "needed", type: "uint256" }, { name: "max", type: "uint256" }] },
  { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
  { type: "error", name: "UUPSUnsupportedProxiableUUID", inputs: [{ name: "slot", type: "bytes32" }] },
  { type: "error", name: "UnauthorizedDynamicLPFeeUpdate", inputs: [] },
  { type: "error", name: "UnauthorizedPoolCreator", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "UnexpectedUser", inputs: [] },
  { type: "error", name: "UnknownBatch", inputs: [{ name: "batchId", type: "uint256" }] },
  { type: "error", name: "UnknownJurisdiction", inputs: [{ name: "country", type: "bytes2" }] },
  { type: "error", name: "UnknownProject", inputs: [{ name: "projectId", type: "uint256" }] },
  { type: "error", name: "UnknownReport", inputs: [{ name: "reportId", type: "uint256" }] },
  { type: "error", name: "UntrustedRouter", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "VintageMismatch", inputs: [{ name: "expected", type: "uint16" }, { name: "actual", type: "uint16" }] },
  { type: "error", name: "WrappedError", inputs: [{ name: "target", type: "address" }, { name: "selector", type: "bytes4" }, { name: "reason", type: "bytes" }, { name: "details", type: "bytes" }] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  // Solidity 內建的兩個：revert("...") 與 assert 失敗
  { type: "error", name: "Error", inputs: [{ name: "message", type: "string" }] },
  { type: "error", name: "Panic", inputs: [{ name: "code", type: "uint256" }] },
] as const;
